import Head from 'next/head';

export const config = { amp: true };

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Amp Page</h1>
      </main>
    </>
  );
}
